name: "FlightBERT++"

lon_size: 18
lat_size: 16
alt_size: 11
spdx_size: 11
spdy_size: 11
spdz_size: 11

delta_lon_size: 8
delta_lat_size: 8
delta_alt_size: 8
delta_spdx_size: 9
delta_spdy_size: 9
delta_spdz_size: 6

lat_embed: 128
lon_embed: 128
alt_embed: 128
spdx_embed: 128
spdy_embed: 128
spdz_embed: 128
dis_n_embed: 64

n_embd: 768
attn_pdrop: 0.1
embd_pdrop: 0.1
resid_pdrop: 0.1
encoder_drop: 0.1

n_en_layer: 4
n_de_layer: 2
n_head: 4

use_graycode: true