name: transformer
params:
  _target_: models.architectures.transformer.TrajectoryTransformer
  batch_first: true

  d_model: 128
  nhead: 8
  num_encoder_layers: 4
  num_decoder_layers: 6
  dim_feedforward: 512
  dropout: 0.1
  max_input_len: 10
  max_output_len: 80