name: transformer
params:
  _target_: models.architectures.transformer.TrajectoryTransformer
  batch_first: true

  encoder_input_dim: 8  # absolute positions + deltas + threshold features (x, y, alt, dx, dy, dalt, thr_dx, thr_dy)
  decoder_input_dim: 5  # deltas + threshold features (dx, dy, dalt, thr_dx, thr_dy)
  output_dim: 3         # predicted deltas only (dx, dy, dalt)
  d_model: 128
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 512
  dropout: 0.1
  max_input_len: 15
  max_output_len: 120