name: transformer
params:
  _target_: models.transformer.transformer.TrajectoryTransformer
  batch_first: true

  input_dim: 6
  d_model: 128
  nhead: 8
  num_encoder_layers: 4
  num_decoder_layers: 4
  dim_feedforward: 512
  dropout: 0.0
  max_input_len: 15
  max_output_len: 120