name: january

train_inputs_path: "/sc/projects/sci-naumann/chair/tim.riedel/FlightFusion/datasets/EDDB-january/trajectories/EDDB_trajectories-inputs_2024-01-01_2024-01-31.parquet"
train_horizons_path: "/sc/projects/sci-naumann/chair/tim.riedel/FlightFusion/datasets/EDDB-january/trajectories/EDDB_trajectories-horizons_2024-01-01_2024-01-31.parquet"
test_inputs_path: "/sc/projects/sci-naumann/chair/tim.riedel/FlightFusion/datasets/EDDB-january/trajectories/EDDB_trajectories-inputs_2024-01-01_2024-01-31.parquet"
test_horizons_path: "/sc/projects/sci-naumann/chair/tim.riedel/FlightFusion/datasets/EDDB-january/trajectories/EDDB_trajectories-horizons_2024-01-01_2024-01-31.parquet"


input_time_minutes: 5
horizon_time_minutes: 40
resampling_rate_seconds: 20
