name: single_day

train_inputs_path: /sc/home/tim.riedel/masterthesis/assets/datasets/EDDB-single-day/trajectories/EDDB_trajectories-inputs_2024-01-01_2024-01-01.parquet
train_horizons_path: /sc/home/tim.riedel/masterthesis/assets/datasets/EDDB-single-day/trajectories/EDDB_trajectories-horizons_2024-01-01_2024-01-01.parquet
test_inputs_path: /sc/home/tim.riedel/masterthesis/assets/datasets/EDDB-single-day/trajectories/EDDB_trajectories-inputs_2024-01-01_2024-01-01.parquet
test_horizons_path: /sc/home/tim.riedel/masterthesis/assets/datasets/EDDB-single-day/trajectories/EDDB_trajectories-horizons_2024-01-01_2024-01-01.parquet

flightinfo_path: /sc/home/tim.riedel/masterthesis/assets/datasets/EDDB-single-day/flightinfo/EDDB_flightinfo_2024-01-01_2024-01-01.parquet

input_time_minutes: 5
horizon_time_minutes: 40
resampling_rate_seconds: 30