# Execution configuration for the FlightBERT++ model
# Includes all settings needed for model execution

defaults:
  - /base_config
  - model: flight_bert
  - dataset: january
  - _self_

optimizer:
  _target_: torch.optim.Adam
  learning_rate: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  step_size: 20
  gamma: 0.7

trainer:
  max_epochs: 50

dataset:
  dataloader:
    batch_size: 3072